#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul 17 15:45:57 2021

@author: Josh Liu
"""

def binSearch1(A, t): 
    """
    Binary search that returns the minimum index i, such that A[i] >= target. If no such element exists, return N, the length of A.
    Input: A, a list of elements to be searched. MUST BE sorted in ascending order.
            t: target;
            
    Returns: an integer
    """
    
    
    l, r = 0, len(A)
    while l < r:
        m = (l + r) // 2 # difference (1)
        if A[m] >= t:
            r = m
        else:
            l = m + 1
    return l
A=[0,1,2,3]
binSearch1(A, 10000)

def binSearch2(A, t):
    """
    Binary search that returns the maximum index i, such that A[i] <= target. If no such element exists, return -1.
    Input: A, a list of elements to be searched. MUST BE sorted in ascending order.
            t: target;
            
    Returns: an integer
    """
    
  
    l, r = -1, len(A) - 1
    while l < r:
        m = (l + r) // 2 + (l + r) % 2 # difference (1)
        if A[m] <= t:
            l = m
        else:
            r = m - 1
    return r
A = [0, 1, 2, 3]
binSearch2(A, -.1)