#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 27 21:15:57 2021

@author: liuzhao
"""

uf =   {a: a for a in string.ascii_lowercase}
def find(t):
    global uf
    if uf[t] != t:
        uf[t] = find(uf[t])
    return uf[t]
def union(u, v):
    global uf
    u, v = find(u), find(v)
    if u != v:
        uf[u] = find(v)
